language: en-US

reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - WIP
      - DRAFT
  request_changes_workflow: true
  path_filters:
    - "!dist/"
    - "!build/"
    - "!target/"
    - "!node_modules/"
    - "src/"
    - "src-tauri/"
  tools:
    eslint:
      enabled: true
    biome:
      enabled: true
    ruff:
      enabled: true
    shellcheck:
      enabled: true
    hadolint:
      enabled: true
    markdownlint:
      enabled: true
